name: purchasepoint
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  logger: ^2.3.0
  lottie: ^3.1.2
  connectivity_plus: ^6.0.3
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  #Product Specific
  carousel_slider: ^4.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

  #App Related
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2

  #Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/purchasepoint-light.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  
  assets:
    - assets/icons/
    - assets/icons/brands/
    - assets/logos/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/signup/
    - assets/icons/categories/
    - assets/images/banners/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
    - family: coolvetica
      fonts:
        - asset: assets/fonts/coolvetica-rg-it.otf
          style: italic
          weight: 400
        - asset: assets/fonts/coolvetica-rg.otf
          weight: 400
  
  
  
